version: '3.7'

services:
  leo-iot-web:
    depends_on: [ leo-iot-db, leo-iot-server ]
    image: ghcr.io/leo-iot/leo-iot-web/app
    build: leo-iot-web
    container_name: leo-iot-web
    ports:
      - "80:80"
  leo-iot-server:
    depends_on: [leo-iot-db]
    image: ghcr.io/leo-iot/leo-iot-server/app
    build: leo-iot-server
    container_name: leo-iot-server
    ports:
      - "8080:8080"  # the HTTP endpoint
  leo-iot-db:
    image: ghcr.io/leo-iot/leo-iot-database/app
    build: leo-iot-database
    container_name: leo-iot-database
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
      POSTGRES_DB: db
    volumes:
      - ./data/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
