apiVersion: apps/v1
kind: Deployment
metadata:
  name: leo-iot-backend
spec:
  selector:
    matchLabels:
      app: leo-iot-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: leo-iot-backend
    spec:
      containers:
        - name: leo-iot-backend
          image: "ghcr.io/leo-iot/leo-iot-server-k8s/app:latest"
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: leo-iot-backend-sv
spec:
  selector:
    app: leo-iot-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: leo-iot-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: leoiot.kube
      http:
        paths:
          - path: /j.rathberger/backend(/|$)(.*)$
            pathType: Prefix
            backend:
              service:
                name: leo-iot-backend-sv
                port:
                  number: 8080
