apiVersion: apps/v1
kind: Deployment
metadata:
  name: leo-iot-backend
spec:
  selector:
    matchLabels:
      app: leo-iot-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: leo-iot-backend
    spec:
      containers:
        - name: leo-iot-backend
          image: "ghcr.io/leo-iot/leo-iot-server/app:latest"
          ports:
            - name: http
              containerPort: 8080
