kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: leo-iot-database-pv-claim
  labels:
    app: leo-iot-database
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: leo-iot-database
spec:
  selector:
    matchLabels:
      app: leo-iot-database
  replicas: 1
  template:
    metadata:
      labels:
        app: leo-iot-database
    spec:
      containers:
        - name: leo-iot-database
          image: "ghcr.io/leo-iot/leo-iot-database/app:latest"
          ports:
            - name: http
              containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: app
            - name: POSTGRES_USER
              value: app
            - name: POSTGRES_DB
              value: db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: timescaledb
      volumes:
        - name: timescaledb
          persistentVolumeClaim:
            claimName: leo-iot-database-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: leo-iot-db
spec:
  selector:
    app: leo-iot-database
  ports:
    - port: 5432
      targetPort: 5432
  type: LoadBalancer
