apiVersion: apps/v1
kind: Deployment
metadata:
  name: value-sim
spec:
  selector:
    matchLabels:
      app: value-sim
  replicas: 1
  template:
    metadata:
      labels:
        app: value-sim
    spec:
      containers:
        - name: value-sim
          image: "ghcr.io/leo-iot/leo-iot-value-sim-k8s/app:latest"
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: value-sim-sv
spec:
  selector:
    app: value-sim
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: value-sim-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: leoiot.kube
      http:
        paths:
          - path: /j.rathberger/value-sim(/|$)(.*)$
            pathType: Prefix
            backend:
              service:
                name: value-sim-sv
                port:
                  number: 8080
